# Generated by Django 5.0.2 on 2024-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_cashback_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_notification_required',
            field=models.BooleanField(default=True),
        ),
    ]
