version: "3"

services:
  app:
    command: >
      sh -c "
          sleep 10 &&
          python3 manage.py migrate &&
          python3 manage.py createsuperuser --noinput &&
          python3 manage.py runserver"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE_NAME
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: >
      sh -c " sleep 10 && celery -A online_shop worker -l info"
    volumes:
      - .:/app
    depends_on:
      - db
      - app
      - redis
volumes:
  postgres_data:
