# Generated by Django 4.2.11 on 2024-04-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_notif_sent',
            field=models.BooleanField(default=False),
        ),
    ]
