name: Test Django CI

on:
  push:
    branches: [ CI-test ]
  pull_request:
    branches: [ CI-test, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up .env
        run: |
          echo "${{secrets.ENV_FILE}}" > .env

      - name: Run DB
        run: |
          docker-compose -f docker-compose.yml up -d db
      - name: Wait for DB
        run: |
          until docker exec -t $(docker ps -q -f name=shop_db_1) pg_isready -h localhost -p 5432; do
            echo "Waiting for database to be ready...";
            sleep 5;
          done
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt