name: Django CI

on:
  push:
    branches: [ CI-test ]
  pull_request:
    branches: [ CI-test ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.0-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up .env
        run: |
          echo "${{secrets.ENV_FILE}}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for DB
        run: |
          sleep 10
          until docker exec -t $(docker ps -q -f name=postgres) pg_isready -h localhost -p 5432; do
            echo "Waiting for database to be ready...";
            sleep 5;
          done

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Lint with Prospector
        run: |
          prospector || true

      - name: Run tests
        run: |
          pytest
